#version: 0.2

#phases:
#  pre_build:
#    commands:
#      - echo Nothing to do in the pre_build phase...
#  build:
#   commands:
#      - echo Build started on `date`
#      - mvn install
#
#artifacts:
#  files:
#    - '**/LoginWebApp-1.war'
#    - 'appspec.yaml'
#  discard-paths: yes

version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
